version: '3.9'  # optional since Compose v1.27.0

services:
  kong-database:
    image: postgres:9.5
    container_name: kong-postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=e9dbc9a39c5532647a0e722bb0a87a3d86063bad
      - POSTGRES_DB=kong
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
