version: '3.3'

services:
  database:
    image: postgres:14.1-alpine
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - /home/deep/sunking/data/lib/postgres/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: e9dbc9a39c5532647a0e722bb0a87a3d86063bad
      POSTGRES_DB: dev_skp_wallet_management
    networks:
      - um_network
